# Generated by Django 2.0.6 on 2018-06-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users_app.User')),
            ],
        ),
    ]
