# Generated by Django 2.0.6 on 2018-06-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(default='fish', max_length=255),
            preserve_default=False,
        ),
    ]
